=== dhuzjak/gsn34/endymion_configuration/gsn_config.dtd
<!ELEMENT configuration (gsn+, storage?)>

<!ELEMENT gsn (ipAddress, port, username, password, connectionType, vsensors, alarms?)>
<!ELEMENT ipAddress (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT connectionType (#PCDATA)>

<!ELEMENT alarms (alarm+)>

<!ELEMENT alarm (send-to+)>
<!ATTLIST alarm name CDATA #REQUIRED>
<!ATTLIST alarm after CDATA "24h">
<!ATTLIST alarm only-once (false|true) "false">
<!ATTLIST alarm alarm-type (email|stdout|mqtt) "stdout">
<!ATTLIST alarm alarm-id CDATA "1">

<!ELEMENT send-to (#PCDATA)>

<!ELEMENT vsensors (vsensor*)>
<!ATTLIST vsensors sampling-time CDATA "1h">
<!ATTLIST vsensors sampling-rate CDATA "1">
<!ATTLIST vsensors only-last-value (false|true) "false">
<!ATTLIST vsensors read-sensors (all|part) "all">

<!ELEMENT vsensor (fields?, alarms?)>
<!ATTLIST vsensor vsname CDATA #REQUIRED>
<!ATTLIST vsensor sampling-time CDATA #IMPLIED>
<!ATTLIST vsensor sampling-rate CDATA #IMPLIED>
<!ATTLIST vsensor only-last-value (false|true) #IMPLIED>
<!ATTLIST vsensor read-data-fields (all|part) "all">

<!ELEMENT fields (data-field*)>
<!ELEMENT data-field EMPTY>

<!ATTLIST data-field name CDATA #REQUIRED>
<!--<!ATTLIST data-field unit (int|double|string) #REQUIRED>-->

<!ELEMENT storage EMPTY>
<!ATTLIST storage url CDATA #REQUIRED>
<!ATTLIST storage username CDATA #REQUIRED>
<!ATTLIST storage password CDATA #REQUIRED>

=== dhuzjak/gsn34/endymion_configuration/gsn_config.xml
<?xml version="1.0"?>
<!DOCTYPE configuration SYSTEM "endymion_configuration/gsn_config.dtd">
<configuration>
    <gsn>
        <ipAddress>127.0.0.1</ipAddress>
        <port>22001</port>
        <username>admin</username>
        <password>admin</password>
        <connectionType>http</connectionType>
        
        <vsensors sampling-time="1m" sampling-rate="1" only-last-value="false" read-sensors="all">
            <vsensor vsname="mqttsubscribetestvs" sampling-time="1m" read-data-fields="all" only-last-value="true">
                <!--
                <alarms>
                    <alarm name="alarm_mqtt_subscribetest" after="1m" only-once="false" alarm-type="mqtt" alarm-id="2">
                        <send-to>RASIP/Endymion/alarms</send-to>
                        
                    </alarm>
                </alarms>
                -->
            </vsensor>
        </vsensors>
        
        <alarms>
            <alarm name="alarm_GSN_90" after="1m" only-once="true" alarm-type="mqtt" alarm-id="30">
                <send-to>RASIP2/Endymion/alarms</send-to>
                
            </alarm>
        </alarms>
    
    </gsn>
    <!--
    <gsn>
        <ipAddress>192.168.5.84</ipAddress>
        <port>22001</port>
        <username>admin</username>
        <password>admin</password>
        <connectionType>http</connectionType>
        
        <vsensors sampling-time="1m" sampling-rate="1" only-last-value="false" read-sensors="all">
            <vsensor vsname="pirsensor" sampling-time="1m" read-data-fields="all" only-last-value="true">
                
            </vsensor>
        </vsensors>
        
        <alarms>
            <alarm name="pirsensor" after="1m" only-once="true" alarm-type="mqtt" alarm-id="62">
                <send-to>RASIP/Endymion/alarms</send-to>
                
            </alarm>
        </alarms>
        
    </gsn>-->

	<!--
    <gsn>
        <ipAddress>161.53.67.210</ipAddress>
        <port>1443</port>
        <username>admin</username>
        <password>admin</password>
        <connectionType>https</connectionType>

        <vsensors sampling-time="5m" sampling-rate="1" only-last-value="true" read-sensors="all">
        </vsensors>
		
		<alarms>
            <alarm name="alarm_GSN_210" after="12h" only-once="true">
                <send-to>nikola.kurdija@gmail.com</send-to>
                <send-to>nikola.kurdija@fer.hr</send-to>
            </alarm>
        </alarms>

    </gsn>
    <gsn>
        <ipAddress>data.permasense.ch</ipAddress>
        <port>80</port>
        <username></username>
        <password></password>
        <connectionType>http</connectionType>

        <vsensors sampling-time="30m" sampling-rate="1" only-last-value="false" read-sensors="part">
            <vsensor vsname="dirruhorn_camera_pos5__scaled" read-data-fields="part">
                <fields>
                    <data-field name="device_id" />
                    <data-field name="jpeg_scaled" />
                </fields>
            </vsensor>
        </vsensors>

    </gsn>-->
</configuration>
